# Generated by Django 3.1.6 on 2021-02-14 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_exam_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='previous_question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API.question'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('Question', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='API.question')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='question_answer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='API.answer'),
            preserve_default=False,
        ),
    ]
