# Generated by Django 3.1.6 on 2021-04-11 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_auto_20210405_0012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='question',
            name='Exam',
        ),
        migrations.AddField(
            model_name='exam',
            name='attendance',
            field=models.ManyToManyField(related_name='attendance', to='API.Student'),
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_duration',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_name',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_startdate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='examiner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API.examiner'),
        ),
        migrations.AddField(
            model_name='exam',
            name='question',
            field=models.ManyToManyField(to='API.Question'),
        ),
        migrations.AddField(
            model_name='exam',
            name='students',
            field=models.ManyToManyField(related_name='allowed_students', to='API.Student'),
        ),
    ]
