# Generated by Django 3.1.6 on 2021-04-13 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_auto_20210411_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='Question',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='attendance',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='question',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='students',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_answer',
        ),
        migrations.AddField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='API.question'),
        ),
        migrations.AddField(
            model_name='question',
            name='exam',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='API.exam'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='examiner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='API.examiner'),
        ),
        migrations.AlterField(
            model_name='question',
            name='mark',
            field=models.FloatField(null=True),
        ),
    ]
