# Generated by Django 3.1.6 on 2021-04-29 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0013_auto_20210415_2214'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.answer')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.exam')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.student')),
            ],
        ),
        migrations.CreateModel(
            name='ExamResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.FloatField()),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.student')),
            ],
        ),
    ]
