# Generated by Django 3.1.6 on 2021-05-08 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0015_allowedstudents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allowedstudents',
            name='students',
        ),
        migrations.AddField(
            model_name='allowedstudents',
            name='students',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='API.student'),
            preserve_default=False,
        ),
    ]
