# Generated by Django 3.1.6 on 2021-05-08 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0016_auto_20210508_2037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allowedstudents',
            old_name='students',
            new_name='student',
        ),
    ]
