# Generated by Django 3.1.6 on 2021-05-09 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0017_auto_20210508_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_message', models.TextField()),
            ],
        ),
    ]
