# Generated by Django 3.1.6 on 2021-05-14 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0019_auto_20210514_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='examiner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='API.examiner'),
        ),
    ]
