# Generated by Django 3.1.6 on 2021-05-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0021_allowedstudents_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowedstudents',
            name='attendance',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='allowedstudents',
            name='enter_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='allowedstudents',
            name='finish_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
