# Generated by Django 3.1.6 on 2021-05-18 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0022_auto_20210518_1636'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allowedstudents',
            old_name='finish_time',
            new_name='submit_time',
        ),
    ]
