# Generated by Django 3.1.6 on 2021-07-09 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0025_examsupervisors'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammingTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=255)),
                ('test_startdate', models.DateTimeField()),
                ('test_duration', models.FloatField()),
                ('examiner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='API.examiner')),
            ],
        ),
    ]
