# Generated by Django 3.1.6 on 2021-07-09 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0026_programmingtest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammingQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('test', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='API.programmingtest')),
            ],
        ),
    ]
