# Generated by Django 3.1.6 on 2021-07-10 14:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0027_programmingquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('Supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.supervisor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.student')),
            ],
        ),
    ]
