# Generated by Django 3.1.6 on 2021-07-10 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0028_violation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='violation',
            old_name='Supervisor',
            new_name='supervisor',
        ),
        migrations.RenameField(
            model_name='violation',
            old_name='description',
            new_name='violation',
        ),
    ]
