# Generated by Django 3.1.6 on 2021-07-10 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0029_auto_20210710_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='violation',
            name='exam',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='API.exam'),
            preserve_default=False,
        ),
    ]
